// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7FVMu1XeNYVorDa4gmb2jH8kI2WMUYsU',
    appId: '1:82480771693:android:2f30d76fa5f709f09b4564',
    messagingSenderId: '82480771693',
    projectId: 'rulebook804',
    databaseURL: 'https://rulebook804-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rulebook804.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSK6xzS5hiPvggAux0zumhM-3p4Q_37gs',
    appId: '1:82480771693:ios:de8ee55ff474bc4a9b4564',
    messagingSenderId: '82480771693',
    projectId: 'rulebook804',
    databaseURL: 'https://rulebook804-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rulebook804.firebasestorage.app',
    androidClientId: '82480771693-mhne7e6q8ofloa700mq7kv31re8h42g9.apps.googleusercontent.com',
    iosClientId: '82480771693-uek09oo57cip2m9r7gn4afjduqpdu6vd.apps.googleusercontent.com',
    iosBundleId: 'com.goflow.billcoder.driver',
  );
}
