// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOOnMuX_F3PvR-35hpHZWDDK-bweq5jys',
    appId: '1:1005394126485:android:b1f9ceaa73255949eadd9c',
    messagingSenderId: '1005394126485',
    projectId: 'movil-ya-d19c0',
    databaseURL: 'https://movil-ya-d19c0-default-rtdb.firebaseio.com',
    storageBucket: 'movil-ya-d19c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiHFiVS1J97xEkHwh0Dd1yqMUEn6D6FpQ',
    appId: '1:1005394126485:ios:120bf113893bc3eceadd9c',
    messagingSenderId: '1005394126485',
    projectId: 'movil-ya-d19c0',
    databaseURL: 'https://movil-ya-d19c0-default-rtdb.firebaseio.com',
    storageBucket: 'movil-ya-d19c0.firebasestorage.app',
    androidClientId: '1005394126485-4lu33smpecfccpb2m6i8vosc0b1mmqcc.apps.googleusercontent.com',
    iosClientId: '1005394126485-t8qa1pnr40di5enprj14k9dtbd1no8ft.apps.googleusercontent.com',
    iosBundleId: 'com.goflow.billcoder.driver',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoW-5DuAoFyd93JilOtjmQvP2DdBWFAPw',
    appId: '1:1005394126485:web:46573473de000d36eadd9c',
    messagingSenderId: '1005394126485',
    projectId: 'movil-ya-d19c0',
    authDomain: 'movil-ya-d19c0.firebaseapp.com',
    databaseURL: 'https://movil-ya-d19c0-default-rtdb.firebaseio.com',
    storageBucket: 'movil-ya-d19c0.firebasestorage.app',
    measurementId: 'G-LFX3PSVED5',
  );

}